### ISSUE TITLE
notes is not `go get`-able

### ISSUE THREAD

**Issue by jbpratt** [prdpx7/notes-cli#3]
```
~ go get github.com/prdpx7/notes-cli

go: downloading github.com/prdpx7/notes-cli v0.0.0-20200429185458-71195b736291
go: github.com/prdpx7/notes-cli upgrade => v0.0.0-20200429185458-71195b736291
go get: github.com/prdpx7/notes-cli@v0.0.0-20200429185458-71195b736291: parsing go.mod:
	module declares its path as: notes
	        but was required as: github.com/prdpx7/notes-cli
```

**Comment by prdpx7** [comment]
I think this project is still in very infant stage, and not in form of a re-usable go-package(to be used in some other go-project).
Also, I can't find any use-case to make this as go-package(btw i'm happy to hear your idea on this). 
so, i intentionally made it not `go get` -able as of right now.
although you can `git clone` it and copy the project folder into your `$GOPATH`.

**Comment by jbpratt** [comment]
Hi @prdpx7 , 

I'm not actually trying to use it as a package but instead just build and install through the go tool chain. https://github.com/prdpx7/notes-cli/pull/1#issuecomment-620583008 I believe either renaming the repository or rename the module will solve this issue. `go get` handles all of the cloning and building! 

Very cute tool, nice work.

**Comment by prdpx7** [comment]
Hi @jbpratt78 ,

Thanks for the info.I have pushed the changes.
let me know, if it's need any further improvement.

**Comment by jbpratt** [comment]
> Hi @jbpratt78 ,
> 
> Thanks for the info.I have pushed the changes.
> let me know, if it's need any further improvement.

My apologies, I should have been more descriptive. I am getting a similar but different error:
```
	module declares its path as: notes-cli
	        but was required as: github.com/prdpx7/notes-cli
```
`go get` will look at `github.com/user/repo` for a module defined similar to [this](https://github.com/mattn/goreman/blob/master/go.mod#L1) then builds and installs that module.

Sorry for not being more clear, and thank you!

**Comment by dmorn** [comment]
I'm back again (I was answering to your comment @prdpx7 and I saw the issue), this is what I was talking about with [this pull request](https://github.com/prdpx7/notes-cli/pull/2) 😆 go get for the gophers!

**Comment by prdpx7** [comment]
Hey @jbpratt78, 
I fixed the issue, and now you can do `go get github.com/prdpx7/notes-cli`.

@jecoz, i really appreciate the work you did but the project is still in-progress. 
Let me add some really good reusable methods in main module (& some features in cli) first, and then i'll restructure the project more in `go` way.
